apps:
  pages:
    - number: 1
      items:
        - App Store
        - Notes
        - folder: Mac Stock Apps
          pages:
            - number: 1
              items:
                - Mail
                - Contacts
                - Reminders
                - FaceTime
                - Messages
                - Find My
                - Maps
                - Photo Booth
                - Photos
                - Preview
                - Music
                - Podcasts
                - TV
                - Voice Memos
                - Numbers
                - Mission Control
                - Keynote
                - Books
                - Dictionary
                - Home
                - Pages
                - Siri
                - Stocks
                - Calendar
                - Safari
                - Clock
                - Weather
                - News
                - iPhone Mirroring
                - Passwords
                - Tips
                - Itsycal
                - Hidden Bar
                - Rectangle
        - folder: Other
          pages:
            - number: 1
              items:
                - Shortcuts
                - QuickTime Player
                - TextEdit
                - Grapher
                - Time Machine
                - Font Book
                - Stickies
                - Image Capture
                - VoiceOver Utility
                - AirPort Utility
                - Migration Assistant
                - Terminal
                - Activity Monitor
                - Console
                - System Information
                - Automator
                - Script Editor
                - Disk Utility
                - Digital Color Meter
                - ColorSync Utility
                - Screenshot
                - Bluetooth File Exchange
                - Audio MIDI Setup
                - The Unarchiver
                - Transmission
                - Screen Sharing
                - Print Center
                - Creative Cloud Content Manager
                - Creative Cloud Desktop App
                - CC Troubleshooter
                - Creative Cloud Installer
                - Creative Cloud Helper
                - Creative Cloud
                - Adobe Creative Cloud Diagnostics
                - LogiPluginService
            - number: 2
              items:
                - Freeform
                - Parallels Desktop Activation Tool
                - Core Sync
                - Chess
        - folder: Recovery
          pages:
            - number: 1
              items:
                - Disk Drill
                - StellarDataRecovery
                - Smart Switch
                - Aiseesoft iPhone Unlocker for Mac
                - EaseUS Data Recovery Wizard
                - Mac FoneLab Android Data Recovery
                - iOS Toolkit for Mac
                - ReiBoot
                - Mac FoneTrans for iOS
                - Joyoshare UltFix
                - Joyoshare Activation Unlocker
                - Wondershare Repairit
                - Logi Options+
        - Calculator
        - System Settings
        - folder: Web Dev / OSINT
          pages:
            - number: 1
              items:
                - net.downloadhelper.coapp
                - SiteSucker Pro
                - FirmwareUpdateTool
                - Logi Bolt
                - Tor Browser
                - Bitdefender Virus Scanner
                - Blackmagic Disk Speed Test
                - AppCleaner
                - Maccy
                - Raycast
                - Logitech G HUB
                - Parallels Toolbox
                - Blackmagic RAW Speed Test
                - Command X
                - Raindrop.io
        - folder: Communication
          pages:
            - number: 1
              items:
                - Telegram
                - Exodus
                - Thunderbird
                - Viber
                - Discord
                - WhatsApp
                - Tailscale
                - Signal
        - folder: Office
          pages:
            - number: 1
              items:
                - MEGAsync
                - PDF Expert
                - Microsoft Outlook
                - Microsoft PowerPoint
                - Microsoft Word
                - Microsoft Excel
                - Wondershare PDFelement
        - folder: Audio / Video / Media
          pages:
            - number: 1
              items:
                - Audacity
                - HandBrake
                - Spotify
                - Topaz Video AI
                - CleanShot X
                - djay Pro
                - Elmedia Player
                - Blackmagic RAW Player
                - Adobe Audition 2024
                - iZotope RX 11 Audio Editor
                - Audio Hijack
                - Logic Pro
        - folder: Photo Editing
          pages:
            - number: 1
              items:
                - Luminar AI
                - Luminar Neo
                - Remove ON1 NoNoise AI 2023
                - ON1 NoNoise AI 2023
                - ON1 Resize AI 2023
                - BCStudio
                - QR Factory
                - Topaz Photo AI
                - Topaz DeNoise AI
                - Photomator
                - Adobe Photoshop 2024
                - Lyn
                - Image Playground
        - Jellyfin Media Player
        - Google Chrome
        - Firefox
        - iTerm
        - Parallels Desktop
        - 3CX (PWA)
        - Nextcloud
        - Zoho Mail - Desktop
        - ChatGPT
        - AnyDesk
        - dupeguru
        - Visual Studio Code
widgets:
  pages: []
dock_items:
  apps:
    - /System/Applications/Launchpad.app
    - /Applications/Google Chrome.app
    - /Applications/Parallels Desktop.app
    - /Applications/iTerm.app
  others:
    - path: ~/Downloads
      display: 1
      view: 2
      sort: 2
  settings:
    autohide: true
    largesize: 30
    magnification: false
    minimize-to-application: true
    mru-spaces: false
    show-recents: false
    tilesize: 63
desktop: {}
